version: '3.8'
services:
  web:
    container_name: my-mle-template-container
    build: .
    command: bash -c "python -m src.preprocess && python -m src.train && python -m src.predict -m RandomForestClassifier -t smoke && coverage run -m src.unit_tests.test_preprocess && coverage run -m -a src.unit_tests.test_training && coverage report -m && python -m src.server -m RandomForestClassifier"
    ports:
      - 8000:8000
    image: bogdanliutikov/firstdockerfile:latest
    volumes:
      - type: bind
        source: .
        target: /app
